<a href="https://colab.research.google.com/github/Mohan0051/Mohan/blob/main/Numpy_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as n
#create an array
array=n.array([1,2,3,4,5])
print("array:", array)

array: [1 2 3 4 5]


In [ ]:
#0D
a=n.array(4)
print ("0D",a)
ar=n.array([1,25,63,])
print("1D",ar)
arr=n.array([[1,2,3,],[4,5,6]])
print("2D",arr)
print(arr.ndim)
arra=n.array([[[1,2,3],[10,11,12],[7,8,9]]])
print("3D",arra)
print(arra.ndim)
#slicing
print("slicing 1D:",ar[0:2])
print("slicing 2D:",arr[1:2])
print("slicing 3D:",arra[1:2])

0D 4
1D [ 1 25 63]
2D [[1 2 3]
 [4 5 6]]
2
3D [[[ 1  2  3]
  [10 11 12]
  [ 7  8  9]]]
3
slicing 1D: [ 1 25]
slicing 2D: [[4 5 6]]
slicing 3D: []


In [ ]:
#creating arrays with zeros & ones
import numpy as n
n.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#creating ones
n.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
#creat an array with range of values
import numpy as np
d= np.arange(10,26,5)
print(d)

[10 15 20 25]


In [ ]:
#array with evenly spaced values
print(np.linspace(0,2,9))
e=np.full((2,2),7)
print(e)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[7 7]
 [7 7]]


In [ ]:
#identity matrix
f=np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#returns dimension of array
arr=n.array([[1,2,3,],[4,5,6]])
arr.shape

(2, 3)

In [ ]:
#returns the no of dim
arr=n.array([[1,2,3,],[4,5,6]])
print("2D",arr)
print(arr.ndim)
arra=n.array([[[1,2,3],[10,11,12],[7,8,9]]])
print("3D",arra)
print(arra.ndim)

2D [[1 2 3]
 [4 5 6]]
2
3D [[[ 1  2  3]
  [10 11 12]
  [ 7  8  9]]]
3


In [ ]:
#returns tot no of element
arr.size
arra.size

9

In [ ]:
#returns the dtype of element
arr=n.array([[1,2,3,],[4,5,6]])
arra=n.array([[[1,2,3],[10,11,12],[7,8,9]]])
arr.dtype
arra.dtype

dtype('int64')

In [ ]:
#array operations
#addition
# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.add(array1, array2)

#display the result
print("Array 1:", array1)
print("Array 2:", array2)
print("Result of addition:", result)

Array 1: [1 2 3]
Array 2: [4 5 6]
Result of addition: [5 7 9]


In [ ]:
#subtraction
print("sub:",np.subtract(array1,array2))

sub: [-3 -3 -3]


In [ ]:
#multiplication
print("mul:",np.multiply(array1,array2))

mul: [ 4 10 18]


In [ ]:
#divide
print("div",np.divide(array1,array2))
#dot product of two arrays
print(np.dot(array1,array2))

div [0.25 0.4  0.5 ]
32


In [ ]:
#array manipulation
#reshape an array
array=n.array([[[1,2,3],[10,11,12],[7,8,9]]])
print(array.reshape(3,-2))

[[ 1  2  3]
 [10 11 12]
 [ 7  8  9]]


In [ ]:
#concatenation
ar=n.array([1,25,63,])
c=n.array([1,2,5])
print(n.concatenate((c,ar),axis=0))

[ 1  2  5  1 25 63]


In [ ]:
#split an array into sub-arrays
c=n.array([1,2,3,4,5,6])
print(n.split(c,3))
print(n.split(c,2))

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
#transpose an array
arr=n.array([[1,2,3,],[4,5,6]])
n.transpose(arr)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#mathematical function
#sum of the array
import numpy as np
ar=np.array([1,25,63,])
arr=np.array([[1,2,3,],[4,5,6]])
#sum of array)
print(ar.sum())

89


In [ ]:
#min and max
print(ar.min())
print(arr.max(axis=0))

1
[4 5 6]


In [ ]:
#median of array elmnts
print(np.median(c))

3.5


In [ ]:
#mean of array elments
print(ar.mean())

29.666666666666668


In [ ]:
#standard deviation
print(ar.std())

25.525586292102197


In [ ]:
#trignmentry fnc
a=n.array(4)
print(n.sin(a))
print(n.tan(a))
print(n.cos(a))

-0.7568024953079282
1.1578212823495775
-0.6536436208636119


In [ ]:
#inverse trignomentric functions
print(n.arcsin(a))
print(n.arccos(a))
print(n.arctan(a))

nan
nan
1.3258176636680326


<ipython-input-30-6d437b9de5a4>:2: RuntimeWarning: invalid value encountered in arcsin
  print(n.arcsin(a))
<ipython-input-30-6d437b9de5a4>:3: RuntimeWarning: invalid value encountered in arccos
  print(n.arccos(a))


In [ ]:
#random values from a standard normal distribution
np.random.randn(2,2)

array([[-0.04445658,  0.87189741],
       [-1.119051  ,  0.65586332]])

In [ ]:
#random integer
np.random.randint(c)

array([0, 0, 1, 0, 1, 1])

In [ ]:
#shuffle an array
n=np.array([1,23,45,1,5,2])
print(n)
#before shuffle

[ 1 23 45  1  5  2]


In [ ]:
#after shuffle
np.random.shuffle(n)

In [ ]:
#compute the qth percentile
d=np.array([1,2,3,4])
q=45
np.percentile(d,q)

2.35

In [ ]:
#compute the correlation coefficient
np.corrcoef(d)

1.0

In [ ]:
#logical operation
c=np.array([True,False,True])
d=np.array([True,False,False])
np.logical_and(c,d)

array([ True, False, False])

In [ ]:
np.logical_or(c,d)

array([ True, False,  True])

In [ ]:
np.logical_not(c,d)

array([False,  True, False])

In [ ]:
#linear algebra
import numpy as np

# Create a 2x2 matrix
matrix = np.array([[4, 7],
                   [2, 6]])

# Use np.linalg.inv() to compute the inverse
inverse_matrix = np.linalg.inv(matrix)

# Print the original and inverse matrices
print("Original matrix:")
print(matrix)
print("\nInverse matrix:")
print(inverse_matrix)

Original matrix:
[[4 7]
 [2 6]]

Inverse matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
#determinant of the matrix
det_matrix=np.linalg.det(matrix)
print(det_matrix)

10.000000000000002


In [ ]:
#eigenvalues and eigen vectors
eigen_v=np.linalg.eig(matrix)

In [ ]:
#sorting
c=np.array([1,3,4,2,6,5])
np.sort(c)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#creat an array
a=np.array([1,2,3,4,5])
#save the array to a binary file
np.save('saved_array.npy',a)

In [ ]:
#load the array from th binary file
loaded_array=np.load('saved_array.npy')
print("original array:",c)
print("loaded array:",loaded_array)

original array: [1 3 4 2 6 5]
loaded array: [1 2 3 4 5]


In [ ]:
#copying
import numpy as n
a=n.array([1,276,63,])
h=a.view()
n.copy(a)
h=a.copy
print(h)
print(a)
print(arra.sort())

<built-in method copy of numpy.ndarray object at 0x7c2e5c6fa4f0>
[  1 276  63]
None


In [ ]:
#indexing
print(arr[1])
print(a[a<2])

[4 5 6]
[1]


In [ ]:
#array manipulation
i=n.transpose(arr)
print(i)
print(arr.ravel())
print(arra.reshape(3,-2))
print(n.insert(ar,0,2))
print(n.append(arr,arra))
print(n.delete(ar,[2]))

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[ 1  2  3]
 [10 11 12]
 [ 7  8  9]]
[ 2  1 25 63]
[ 1  2  3  4  5  6  1  2  3 10 11 12  7  8  9]
[ 1 25]


In [ ]:
#splitting
c=n.array([1,2,5])

#combining
print(n.concatenate((c,ar),axis=0))
print(n.vstack((c,ar)))
print(n.hstack((c,ar)))
print(n.column_stack((c,ar)))

[ 1  2  5  1 25 63]
[[ 1  2  5]
 [ 1 25 63]]
[ 1  2  5  1 25 63]
[[ 1  1]
 [ 2 25]
 [ 5 63]]


In [ ]:
#arith
print(ar-arr)
print(n.multiply(a, arr))
print(n.exp(a))
print(n.sin(a))
print(n.log(a))
print(n.cos(a))
print(n.divide(a, ar))
print(n.subtract(a, arr))

[[ 0 23 60]
 [-3 20 57]]
[[   1  552  189]
 [   4 1380  378]]
[2.71828183e+000 7.33292098e+119 2.29378316e+027]
[ 0.84147098 -0.44408566  0.1673557 ]
[0.         5.62040087 4.14313473]
[0.54030231 0.89598433 0.98589658]
[ 1.   11.04  1.  ]
[[  0 274  60]
 [ -3 271  57]]


In [ ]:
#comparison
print(a==ar)
print(a<3)
print(n.array_equal(a, arr))

[ True False  True]
[ True False False]
False
